# Generated by Django 3.1.7 on 2021-07-16 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sessions', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=254, null=True, unique=True, verbose_name='email')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('streetname', models.CharField(max_length=30)),
                ('housenr', models.CharField(max_length=30)),
                ('postalcode', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sessions.session')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('expiry_date', models.DateTimeField()),
                ('discount_type', models.CharField(choices=[('Vast bedrag', 'Vast bedrag'), ('Percentage', 'Percentage')], max_length=30)),
                ('discount_percentage', models.IntegerField(null=True)),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('in_stock', models.BooleanField(default=True)),
                ('description', models.TextField()),
                ('jewelry_type', models.CharField(choices=[('Armband', 'Armband'), ('Ketting', 'Ketting'), ('Oorbel', 'Oorbel')], max_length=30)),
                ('look', models.CharField(blank=True, choices=[('Kralen', 'Kralen'), ('Schakelketting', 'Schakelketting')], max_length=30, null=True)),
                ('metal_type', models.CharField(choices=[('Stainless steel goud', 'Stainless steel goud'), ('Stainless steel zilver', 'Stainless steel zilver'), ('Gold plated', 'Gold plated'), ('Silver plated', 'Silver plated')], max_length=30)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('size', models.IntegerField(blank=True, null=True)),
                ('left', models.IntegerField()),
                ('sale', models.BooleanField(default=False)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('active', models.BooleanField(default=True)),
                ('image', models.ManyToManyField(to='webshop.Photo')),
            ],
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=6)),
                ('ordered', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webshop.product')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ordered', models.DateField()),
                ('status', models.CharField(choices=[('Verzonden', 'Verzonden'), ('In behandeling', 'In behandeling'), ('Ontvangen', 'Ontvangen')], max_length=30)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total', models.DecimalField(decimal_places=2, max_digits=5)),
                ('comment', models.TextField(blank=True, null=True)),
                ('shipping', models.CharField(choices=[('Brievenbuspakketje', 'Brievenbuspakketje'), ('Met Track & Trace', 'Met Track & Trace')], max_length=50)),
                ('shipping_costs', models.DecimalField(decimal_places=2, max_digits=5)),
                ('free_shipping', models.BooleanField(default=False)),
                ('payment_option', models.CharField(blank=True, max_length=30)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('orderproduct', models.ManyToManyField(to='webshop.OrderProduct')),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('favoriteproduct', models.ManyToManyField(to='webshop.Product')),
            ],
        ),
    ]
