# Generated by Django 3.1.7 on 2021-08-13 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productcode', models.CharField(max_length=10)),
                ('data', models.JSONField(null=True)),
                ('description', models.CharField(max_length=100)),
                ('units_left', models.IntegerField()),
            ],
        ),
    ]
