# Generated by Django 3.1.7 on 2021-08-13 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0002_inventoryproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryproduct',
            name='data',
        ),
        migrations.AddField(
            model_name='product',
            name='data',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='raw_materials',
            field=models.ManyToManyField(to='webshop.InventoryProduct'),
        ),
    ]
