# Generated by Django 3.1.7 on 2021-08-13 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0003_auto_20210813_0839'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='left',
            new_name='items_left',
        ),
    ]
