# Generated by Django 3.1.7 on 2021-07-17 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0003_product_information'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
