# Generated by Django 3.0.11 on 2021-01-18 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0004_auto_20210118_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.ManyToManyField(blank=True, to='webshop.Color'),
        ),
        migrations.AlterField(
            model_name='product',
            name='look',
            field=models.CharField(blank=True, choices=[('Kralen', 'Kralen'), ('Schakelketting', 'Schakelketting')], max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.IntegerField(blank=True),
        ),
    ]
