# Generated by Django 3.1.7 on 2021-08-13 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0005_photo_first'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='first',
            new_name='first_item',
        ),
    ]
